### ISSUE TITLE
It's not possible to create a program shortcut with arguments

### ISSUE THREAD

**Issue by ghost** [James231/Start-Menu-Manager#1]
I'm trying to create a Firefox shortcut with argument -p Work  ( -p stand for Profile ) but I'm getting an error ( see below )

![Annotation 2020-09-04 184135](https://user-images.githubusercontent.com/47521966/92257741-67cf2300-eede-11ea-8cbd-ee5e26f0336c.png)

**Comment by James231** [comment]
You are right. Good catch!

That's a major issue, so I'll try and release a fix in the next 24 hours.

**Comment by James231** [comment]
[I deleted my previous comment because I mis-read the issue]

If you want to provide arguments, please change the 'Shortcut Type' to 'Command' and it will work correctly

**Comment by ghost** [comment]
Indeed it solves the issues! Thanks for this! Very useful!
