### ISSUE TITLE
Marked as harmful app

### ISSUE THREAD

**Issue by mrahmadusama** [James231/Start-Menu-Manager#10]
Downloaded through edge chromium and after downloading it marked as a harmful app and deleted it. Look into that if you can rest is working great. 
![image](https://user-images.githubusercontent.com/48976847/92328589-39d31580-f07b-11ea-8168-c4942c7ff7c7.png)
Windows 10 v2004

**Comment by mrahmadusama** [comment]
I have reported it safe too
![image](https://user-images.githubusercontent.com/48976847/92328657-b5cd5d80-f07b-11ea-8582-76676e03c3ce.png)

**Comment by James231** [comment]
Marking it safe might help. But sadly there is nothing else I can do about this.

The only way I could fix it, is to digitally sign the file with a signature Defender and other AVs would accept. It that would cost a lot of time and money so isn't worth it for a free project.

Also, releasing it as an app on the Windows Store might help. But it is very unlikely (probably impossible) for an app like this to be accepted into the store without removing some major peices of functionality.

**Comment by mrahmadusama** [comment]
Yeah, got it, Thanks for the app
