### ISSUE TITLE
Not able to add command line parameters

### ISSUE THREAD

**Issue by SezMe** [James231/Start-Menu-Manager#14]
I am trying to create a shortcut to a program I have written that requires a command line parameter like this:
    MyProgram.exe Parameter1, Parameter2

SMM works if I leave off the parameters but that's no help.  If include the parameters, SMM complains that the file path does not exist.  Bummer.

**Comment by James231** [comment]
To provide command line arguments, make sure the 'Shortcut Type' is set to 'Command' not 'Software'.

Software shortcuts are for single executable files which are executed directly, whereas command shortcuts can accept an entire terminal command (including arguments) which is passed to the command line process.

Hopefully that will solve your problem 🙂

**Comment by SezMe** [comment]
After playing around a bit, I discovered that I had to sign out then sign in again.  I have no clue as to why.
